### PR TITLE
Fix C98 warnings

### PR DESCRIPTION
**Pull request by RobLoach**
See https://github.com/libretro/RetroArch/commit/072848445c5bd1298be693e2cf4baecb83444587#commitcomment-30710083

### CODE REVIEW

**Comment by leiradel** [comment]
Thanks for the PR. Only one question: why `RC_FORMAT_FRAMES = 0`? Is it necessary to fix a C98 warning? I guess not, since there are other enums without the `=0`.

**Comment by RobLoach** [comment]
Unsure, that was one of the changes that @twinaphex made. I can remove the `= 0` if it has no change on compilation.

**Comment by RobLoach** [comment]
Fixed in the above commit. Thanks for the explanation!

**Comment by leiradel** [comment]
@RobLoach can you change this PR to target the develop branch? Thanks

**Comment by RobLoach** [comment]
@leiradel There you go :+1:

**Pull request merged**
