### PR TITLE
Add Gamecube to hash initialize iterator for iso format

### PR DESCRIPTION
**Pull request by bozothegeek**
Just to add Gamecube now for 'iso' format in hash initialization for iterator. Thanks in advance for this merge. Tested in pixL (new retro OS ;-)

### CODE REVIEW

**Comment by bozothegeek** [comment]
See for example of result when hash matched well now with any new retroarchivements for gamecube in this OS using pegasus-frontend and a modified GameOS theme including RA display... 
image

**Comment by Jamiras** [comment]
@bozothegeek - have you had a chance to look at the unit test suggestion?

**Comment by bozothegeek** [comment]
> @bozothegeek - have you had a chance to look at the unit test suggestion?

OK, I will check... sorry, I just saw your reply ;-)

**Comment by bozothegeek** [comment]
Hi @Jamiras It's done, I updated the unit test `test_hash_gamecube` as expected, thanks in advance

**Review by Jamiras — APPROVED** [review]

**Comment by bozothegeek** [comment]
@Jamiras Thanks ;-)

**Pull request merged**
