### PR TITLE
expose Game Pak SRAM for GBA

### PR DESCRIPTION
**Pull request by Jamiras**
Implements https://github.com/RetroAchievements/RAIntegration/discussions/1020.

Verified exposure for all four supported GBA cores:

Beetle GBA:
```
[INFO] [MEM] desc[1]: $3000000 (8000): 
[INFO] [MEM] desc[2]: $2000000 (40000): 
[INFO] [MEM] desc[3]: $e000000 (10000): 
[INFO] [MEM] desc[4]: $6000000 (20000): 
[INFO] [MEM] desc[5]: $5000000 (0400): 
[INFO] [MEM] desc[6]: $7000000 (0400): 
[INFO] [MEM] desc[7]: $4000000 (0400): 
[INFO] [MEM] Registered 0x8000 bytes of SYSTEM RAM at $000000 (descriptor 1, offset 0x000000)
[INFO] [MEM] Registered 0x40000 bytes of SYSTEM RAM at $008000 (descriptor 2, offset 0x000000)
[INFO] [MEM] Registered 0x10000 bytes of SRAM at $048000 (descriptor 3, offset 0x000000)
```

VBA-Next:
```
[INFO] [MEM] desc[1]: $000000 (4000): BIOS
[INFO] [MEM] desc[2]: $2000000 (40000): EWRAM
[INFO] [MEM] desc[3]: $3000000 (8000): IWRAM
[INFO] [MEM] desc[4]: $4000000 (0400): IOMEM
[INFO] [MEM] desc[5]: $5000000 (0400): PALRAM
[INFO] [MEM] desc[6]: $6000000 (18000): VRAM
[INFO] [MEM] desc[7]: $7000000 (0400): OAM
[INFO] [MEM] desc[8]: $8000000 (400000): ROM-WS0
[INFO] [MEM] desc[9]: $a000000 (400000): ROM-WS1
[INFO] [MEM] desc[10]: $c000000 (400000): ROM-WS2
[INFO] [MEM] desc[11]: $e000000 (10000): SRAM
[INFO] [MEM] Registered 0x8000 bytes of SYSTEM RAM at $000000 (descriptor 3, offset 0x000000)
[INFO] [MEM] Registered 0x40000 bytes of SYSTEM RAM at $008000 (descriptor 2, offset 0x000000)
[INFO] [MEM] Registered 0x10000 bytes of SRAM at $048000 (descriptor 11, offset 0x000000)
```

VBA-M:
```
[INFO] [MEM] desc[1]: $3000000 (8000): 
[INFO] [MEM] desc[2]: $2000000 (40000): 
[INFO] [MEM] desc[3]: $e000000 (8000): 
[INFO] [MEM] desc[4]: $8000000 (400000): 
[INFO] [MEM] desc[5]: $a000000 (400000): 
[INFO] [MEM] desc[6]: $c000000 (400000): 
[INFO] [MEM] desc[7]: $000000 (4000): 
[INFO] [MEM] desc[8]: $6000000 (18000): 
[INFO] [MEM] desc[9]: $5000000 (0400): 
[INFO] [MEM] desc[10]: $7000000 (0400): 
[INFO] [MEM] desc[11]: $4000000 (0400): 
[INFO] [MEM] Registered 0x8000 bytes of SYSTEM RAM at $000000 (descriptor 1, offset 0x000000)
[INFO] [MEM] Registered 0x40000 bytes of SYSTEM RAM at $008000 (descriptor 2, offset 0x000000)
[INFO] [MEM] Registered 0x8000 bytes of SRAM at $048000 (descriptor 3, offset 0x000000)
[INFO] [MEM] Could not map region starting at $050000
[INFO] [MEM] Registered 0x8000 bytes of SRAM at $050000 (null filler)
```

mGBA:
```
[INFO] [MEM] desc[1]: $3000000 (8000): 
[INFO] [MEM] desc[2]: $2000000 (40000): 
[INFO] [MEM] desc[3]: $e000000 (20000): 
[INFO] [MEM] desc[4]: $8000000 (400000): 
[INFO] [MEM] desc[5]: $a000000 (400000): 
[INFO] [MEM] desc[6]: $c000000 (400000): 
[INFO] [MEM] desc[7]: $000000 (4000): 
[INFO] [MEM] desc[8]: $6000000 (18000): 
[INFO] [MEM] desc[9]: $5000000 (0400): 
[INFO] [MEM] desc[10]: $7000000 (0400): 
[INFO] [MEM] desc[11]: $4000000 (0400): 
[INFO] [MEM] Registered 0x8000 bytes of SYSTEM RAM at $000000 (descriptor 1, offset 0x000000)
[INFO] [MEM] Registered 0x40000 bytes of SYSTEM RAM at $008000 (descriptor 2, offset 0x000000)
[INFO] [MEM] Registered 0x10000 bytes of SRAM at $048000 (descriptor 3, offset 0x000000)
```

### CODE REVIEW

**Comment by Blazekickn** [comment]
I think pinguu mentioned the Loppi Puzzle Magazine games also save all the flags directly to sram (which is why the sets require one session) so might be worth looking into GB/C as well, although i haven't checked those games for myself yet.

**Comment by Jamiras** [comment]
GB and GBC already expose the entire BUS. GBC even exposes the entire memory that gets paged into $D000-$DFFF so it can be viewed on frames where it's not the selected page. The memory from $A000-$BFFF should be the cartridge RAM (SRAM).

**Comment by CasualPokePlayer** [comment]
SRAM on the GB/C is banked (so A000-BFFF might be the beginning 8KB or another bank, depending on implementation) and potentially unavailable depending on SRAM locking and if the implementation is doing bus reads or bypassing the bus and directly reading.

**Comment by Blazekickn** [comment]
i'll take a look at it later, seems strange to me that there's supposedly nothing in the memory for the puzzle clear flags, im going to assume it's just stored weird.

**Comment by Jamiras** [comment]
> i'll take a look at it later

I'm going to merge this as-is. If you find a problem with GB/C, we can address that later.

**Pull request merged**
